title: Transit Analytics Tools
description: A set of python based code analysing transit's ticketing and scheduling data.
theme: just-the-docs

url: https://github.com/tmr-tau/transit_analytics_tools

aux_links:
  Template Repository: https://github.com/tmr-tau/transit_analytics_tools
