title: Transit Analytics Tools
description: A set of python based code analysing transit's ticketing and scheduling data.
theme: just-the-docs
color_scheme: dark
url: https://github.com/tmr-tau/transit_analytics_tools

repo_url: null  # This should remove the link
repo_label: "View on GitHub"

aux_links:
  View on GitHub: https://github.com/tmr-tau/transit_analytics_tools

# External navigation links
nav_external_links:
  - title: View on GitHub
    url: https://github.com/tmr-tau/transit_analytics_tools
